/**
 * generate-manual.js — Vercel serverless function
 * POST /api/generate-manual
 *
 * Genera el manual de montaje de un pedido: portada Antrade + paginas reales
 * de los PDFs tipo MANUAL_ adjuntos a los productos del pedido (o, si un
 * producto no tiene manuales propios, los del producto representativo de
 * su misma subcategoria). Se sube como ir.attachment al sale.order y,
 * si existe, tambien al crm.lead vinculado.
 *
 * Misma autenticacion que generate-ficha.js (FICHA_SECRET).
 */

'use strict';

const path = require('path');
const fs = require('fs');
const { PDFDocument, rgb, StandardFonts } = require('pdf-lib');
const odoo = require('./_lib/odoo');

const A4_W = 595;
const A4_H = 842;
const MARGIN = 50;

const BLUE    = rgb(0,    0.231, 0.431);
const BLUE_LT = rgb(0.88, 0.93,  0.97);
const GRAY    = rgb(0.45, 0.45,  0.45);
const GRAY_LT = rgb(0.85, 0.85,  0.85);
const BLACK   = rgb(0,    0,     0);
const WHITE   = rgb(1,    1,     1);

const LABELS = {
  es: {
    title:    'MANUAL DE MONTAJE',
    client:   'Cliente',
    order:    'Pedido',
    date:     'Fecha',
    products: 'Productos incluidos',
    footer:   'Documento generado automaticamente por Antrade Servitech SL',
  },
  en: {
    title:    'ASSEMBLY MANUAL',
    client:   'Client',
    order:    'Order',
    date:     'Date',
    products: 'Products included',
    footer:   'Document automatically generated by Antrade Servitech SL',
  },
};

// ---------------------------------------------------------------------------
// Handler principal
// ---------------------------------------------------------------------------
module.exports = async (req, res) => {
  if (req.method === 'OPTIONS') {
    return res.status(204).end();
  }
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const body = req.body || {};
  const order_id = body.order_id || body.id;
  const secret = body.secret || (req.query && req.query.secret);

  if (!process.env.FICHA_SECRET || secret !== process.env.FICHA_SECRET) {
    return res.status(401).json({ error: 'Unauthorized' });
  }
  if (!order_id) {
    return res.status(400).json({ error: 'order_id or id is required' });
  }

  try {
    const result = await buildManual(order_id);

    if (!result.hasAny) {
      return res.status(200).json({
        success: false,
        sin_manual: result.sinManual,
        message: 'No hay manuales disponibles',
      });
    }

    const attName = await uploadToOdoo(order_id, result.pdfBytes, result.opportunityId);
    return res.status(200).json({
      success: true,
      attachment: attName,
      sin_manual: result.sinManual,
    });
  } catch (err) {
    console.error('[generate-manual] ERROR:', err.message);
    return res.status(500).json({ error: err.message });
  }
};

// ---------------------------------------------------------------------------
// buildManual — localiza los manuales aplicables y genera el PDF
// ---------------------------------------------------------------------------
async function buildManual(orderId) {
  // 1. Leer order
  const orders = await odoo.searchRead(
    'sale.order',
    [['id', '=', orderId]],
    ['id', 'name', 'date_order', 'partner_id', 'opportunity_id'],
  );
  if (!orders.length) throw new Error(`sale.order id=${orderId} no encontrado`);
  const order = orders[0];
  const opportunityId = Array.isArray(order.opportunity_id) ? order.opportunity_id[0] : null;

  // 2. Idioma del cliente
  const partners = await odoo.searchRead(
    'res.partner',
    [['id', '=', order.partner_id[0]]],
    ['name', 'lang'],
    { limit: 1 },
  );
  const lang = (partners[0] && partners[0].lang && partners[0].lang.startsWith('es')) ? 'es' : 'en';
  const L = LABELS[lang];

  // 3. Lineas de pedido -> product_ids unicos
  const lines = await odoo.searchRead(
    'sale.order.line',
    [['order_id', '=', orderId], ['product_id', '!=', false]],
    ['product_id', 'product_uom_qty'],
  );
  const prodIds = [...new Set(lines.map(l => l.product_id[0]))];
  if (!prodIds.length) throw new Error('La orden no tiene lineas de producto.');

  // 4. product.product -> product_tmpl_id
  const prods = await odoo.searchRead(
    'product.product',
    [['id', 'in', prodIds]],
    ['id', 'product_tmpl_id'],
  );
  const tmplIds = [...new Set(prods.map(p => p.product_tmpl_id[0]))];

  // 5. product.template -> name, default_code, categ_id
  const tmpls = await odoo.searchRead(
    'product.template',
    [['id', 'in', tmplIds]],
    ['id', 'name', 'default_code', 'categ_id'],
  );
  const tmplById = Object.fromEntries(tmpls.map(t => [t.id, t]));

  // --- PASO A: manuales propios de cada producto ---
  const manualsByTmpl = {};
  const ownManuals = await odoo.searchRead(
    'ir.attachment',
    [
      ['res_model', '=', 'product.template'],
      ['res_id', 'in', tmplIds],
      ['name', 'like', 'MANUAL_%'],
      ['mimetype', '=', 'application/pdf'],
    ],
    ['id', 'name', 'res_id'],
  );
  for (const att of ownManuals) {
    if (!manualsByTmpl[att.res_id]) manualsByTmpl[att.res_id] = [];
    manualsByTmpl[att.res_id].push(att);
  }

  // --- PASO B: para los productos sin manuales propios, buscar en hermanos
  // de la misma categoria (cubre al producto representativo de la familia) ---
  const missingTmplIds = tmplIds.filter(tid => !manualsByTmpl[tid] || !manualsByTmpl[tid].length);
  if (missingTmplIds.length) {
    const categIds = [...new Set(
      missingTmplIds
        .map(tid => tmplById[tid] && tmplById[tid].categ_id)
        .filter(Boolean)
        .map(c => (Array.isArray(c) ? c[0] : c)),
    )];

    if (categIds.length) {
      const siblings = await odoo.searchRead(
        'product.template',
        [['categ_id', 'in', categIds]],
        ['id', 'categ_id'],
      );
      const siblingIdsByCateg = {};
      for (const s of siblings) {
        const cid = Array.isArray(s.categ_id) ? s.categ_id[0] : s.categ_id;
        if (!siblingIdsByCateg[cid]) siblingIdsByCateg[cid] = [];
        siblingIdsByCateg[cid].push(s.id);
      }

      const allSiblingIds = [...new Set(siblings.map(s => s.id))];
      const siblingManuals = allSiblingIds.length
        ? await odoo.searchRead(
            'ir.attachment',
            [
              ['res_model', '=', 'product.template'],
              ['res_id', 'in', allSiblingIds],
              ['name', 'like', 'MANUAL_%'],
              ['mimetype', '=', 'application/pdf'],
            ],
            ['id', 'name', 'res_id'],
          )
        : [];
      const manualsBySiblingId = {};
      for (const att of siblingManuals) {
        if (!manualsBySiblingId[att.res_id]) manualsBySiblingId[att.res_id] = [];
        manualsBySiblingId[att.res_id].push(att);
      }

      for (const tid of missingTmplIds) {
        const tmpl = tmplById[tid];
        if (!tmpl || !tmpl.categ_id) continue;
        const cid = Array.isArray(tmpl.categ_id) ? tmpl.categ_id[0] : tmpl.categ_id;
        const candidateIds = (siblingIdsByCateg[cid] || []).filter(sid => sid !== tid);
        for (const sid of candidateIds) {
          if (manualsBySiblingId[sid] && manualsBySiblingId[sid].length) {
            manualsByTmpl[tid] = manualsBySiblingId[sid];
            break;
          }
        }
      }
    }
  }

  // --- Productos sin manual tras los dos pasos ---
  const sinManual = [];
  for (const tid of tmplIds) {
    if (!manualsByTmpl[tid] || !manualsByTmpl[tid].length) {
      const tmpl = tmplById[tid];
      sinManual.push(tmpl ? (tmpl.default_code || tmpl.name) : `id_${tid}`);
    }
  }

  const tmplIdsWithManual = tmplIds.filter(tid => manualsByTmpl[tid] && manualsByTmpl[tid].length);
  if (!tmplIdsWithManual.length) {
    return { hasAny: false, sinManual, pdfBytes: null, opportunityId };
  }

  // --- Descargar binarios de los manuales seleccionados (sin duplicar ids) ---
  // Una llamada por adjunto, en lotes pequenos (no todas en paralelo ni
  // todas en un unico search_read): cada llamada de _lib/odoo.js abre una
  // conexion XML-RPC nueva, y disparar muchas a la vez (probado: las 40 de
  // este pedido) satura el servidor Odoo, que responde con una pagina de
  // error HTML en vez de XML-RPC valido (error "Unknown XML-RPC tag
  // 'TITLE'"). Con lotes de 4 no se reprodujo el fallo.
  const BATCH_SIZE = 4;
  const allAttIds = [...new Set(
    tmplIdsWithManual.flatMap(tid => manualsByTmpl[tid].map(a => a.id)),
  )];
  const attDataById = {};
  for (let i = 0; i < allAttIds.length; i += BATCH_SIZE) {
    const batch = allAttIds.slice(i, i + BATCH_SIZE);
    const results = await Promise.all(batch.map(async (id) => {
      try {
        const single = await odoo.searchRead(
          'ir.attachment',
          [['id', '=', id]],
          ['id', 'name', 'raw'],
        );
        return single.length ? single[0] : null;
      } catch (e) {
        console.warn(`[generate-manual] No se pudo descargar adjunto id=${id}: ${e.message}`);
        return null;
      }
    }));
    for (const att of results) {
      if (att) attDataById[att.id] = att;
    }
  }

  // --- Construir el PDF ---
  const pdfDoc = await PDFDocument.create();
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const regFont  = await pdfDoc.embedFont(StandardFonts.Helvetica);

  let logoImage = null;
  try {
    const logoPath = path.join(__dirname, '../public/logo-antrade.png');
    const logoBytes = fs.readFileSync(logoPath);
    logoImage = await pdfDoc.embedPng(logoBytes);
  } catch (_) { /* sin logo, continuar */ }

  const dateStr = order.date_order
    ? new Date(order.date_order).toLocaleDateString(lang === 'es' ? 'es-ES' : 'en-GB')
    : '';

  addCoverPage(pdfDoc, boldFont, regFont, logoImage, order, partners[0], tmplIds, tmplById, dateStr, L);

  // Embebe cada adjunto una sola vez aunque varios productos compartan
  // el mismo manual heredado (PASO B).
  const embeddedIds = new Set();
  for (const tid of tmplIdsWithManual) {
    for (const att of manualsByTmpl[tid]) {
      if (embeddedIds.has(att.id)) continue;
      embeddedIds.add(att.id);

      const full = attDataById[att.id];
      if (!full || !full.raw) continue;
      try {
        const pdfBytes = Buffer.from(full.raw, 'base64');
        const src = await PDFDocument.load(pdfBytes, { ignoreEncryption: true });
        const pages = await pdfDoc.copyPages(src, src.getPageIndices());
        for (const p of pages) pdfDoc.addPage(p);
      } catch (e) {
        console.warn(`[generate-manual] No se pudo incrustar ${att.name}: ${e.message}`);
      }
    }
  }

  return { hasAny: true, sinManual, pdfBytes: await pdfDoc.save(), opportunityId };
}

// ---------------------------------------------------------------------------
// addCoverPage
// ---------------------------------------------------------------------------
function addCoverPage(doc, bold, reg, logo, order, partner, tmplIds, tmplById, dateStr, L) {
  const page = doc.addPage([A4_W, A4_H]);

  page.drawRectangle({ x: 0, y: A4_H - 90, width: A4_W, height: 90, color: BLUE });

  if (logo) {
    const dims = logo.scaleToFit(160, 50);
    page.drawImage(logo, {
      x: MARGIN,
      y: A4_H - 90 + (90 - dims.height) / 2,
      width: dims.width,
      height: dims.height,
    });
  }

  page.drawText('Antrade Servitech SL', {
    x: A4_W - MARGIN - 160,
    y: A4_H - 55,
    size: 11,
    font: bold,
    color: WHITE,
  });

  page.drawText(L.title, {
    x: MARGIN,
    y: A4_H - 130,
    size: 22,
    font: bold,
    color: BLUE,
  });

  page.drawLine({
    start: { x: MARGIN, y: A4_H - 140 },
    end:   { x: A4_W - MARGIN, y: A4_H - 140 },
    thickness: 1,
    color: BLUE_LT,
  });

  const infoY = A4_H - 170;
  const rows = [
    [L.client, partner ? partner.name : (order.partner_id[1] || '')],
    [L.order,  order.name],
    [L.date,   dateStr],
  ];
  rows.forEach(([label, value], i) => {
    const y = infoY - i * 22;
    page.drawText(label + ':', { x: MARGIN, y, size: 11, font: bold, color: GRAY });
    page.drawText(String(value), { x: MARGIN + 110, y, size: 11, font: reg, color: BLACK });
  });

  const listY = infoY - rows.length * 22 - 30;
  page.drawText(L.products, { x: MARGIN, y: listY, size: 11, font: bold, color: GRAY });

  let itemY = listY - 22;
  tmplIds.forEach((tid, idx) => {
    const t = tmplById[tid];
    if (!t) return;
    const code = t.default_code ? ` (${t.default_code})` : '';
    const label = safeText(`${idx + 1}. ${t.name}${code}`);
    page.drawText(label, { x: MARGIN + 10, y: itemY, size: 10, font: reg, color: BLACK });
    itemY -= 18;
  });

  drawFooter(page, reg, L.footer, 1);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function drawFooter(page, font, text, pageNum) {
  page.drawLine({
    start: { x: MARGIN, y: 40 },
    end:   { x: A4_W - MARGIN, y: 40 },
    thickness: 0.5,
    color: GRAY_LT,
  });
  page.drawText(safeText(text), { x: MARGIN, y: 26, size: 8, font, color: GRAY });
  if (pageNum !== null) {
    page.drawText(String(pageNum), { x: A4_W - MARGIN - 10, y: 26, size: 8, font, color: GRAY });
  }
}

function safeText(str) {
  return (str || '').replace(/[^\x00-\xFF]/g, '?');
}

// ---------------------------------------------------------------------------
// uploadToOdoo — sube el PDF como ir.attachment al sale.order y, si existe,
// tambien al crm.lead vinculado (opportunity_id).
// ---------------------------------------------------------------------------
async function uploadToOdoo(orderId, pdfBytes, opportunityId) {
  const orders = await odoo.searchRead(
    'sale.order',
    [['id', '=', orderId]],
    ['name'],
    { limit: 1 },
  );
  const orderName = orders.length ? orders[0].name : `order-${orderId}`;
  const attName   = `Manual_Montaje_${orderName}.pdf`;
  const b64 = Buffer.from(pdfBytes).toString('base64');

  const existingSO = await odoo.searchRead(
    'ir.attachment',
    [
      ['res_model', '=', 'sale.order'],
      ['res_id', '=', orderId],
      ['name', '=', attName],
    ],
    ['id'],
  );
  if (existingSO.length) {
    await odoo.execute('ir.attachment', 'unlink', [existingSO.map(a => a.id)]);
  }
  const soAttId = await odoo.create('ir.attachment', {
    name:      attName,
    type:      'binary',
    raw:       b64,
    res_model: 'sale.order',
    res_id:    orderId,
    mimetype:  'application/pdf',
  });

  if (opportunityId && opportunityId > 0) {
    try {
      const existingCRM = await odoo.searchRead(
        'ir.attachment',
        [
          ['res_model', '=', 'crm.lead'],
          ['res_id', '=', opportunityId],
          ['name', '=', attName],
        ],
        ['id'],
      );
      if (existingCRM.length) {
        await odoo.execute('ir.attachment', 'unlink', [existingCRM.map(a => a.id)]);
      }
      await odoo.create('ir.attachment', {
        name:      attName,
        type:      'binary',
        raw:       b64,
        res_model: 'crm.lead',
        res_id:    opportunityId,
        mimetype:  'application/pdf',
      });
      console.log(`[generate-manual] Adjunto subido tambien a crm.lead id=${opportunityId}`);
    } catch (crmErr) {
      console.warn(`[generate-manual] No se pudo subir adjunto a crm.lead id=${opportunityId}: ${crmErr.message}`);
    }
  }

  await addToDocuments(opportunityId, soAttId, attName);

  return attName;
}

// ---------------------------------------------------------------------------
// addToDocuments — copia (envuelve) el adjunto del sale.order como
// documents.document dentro de la subcarpeta 02_Ingenieria del proyecto
// vinculado al lead. Bonus: cualquier fallo se loggea y se ignora, nunca
// debe bloquear la generacion/subida del PDF.
// ---------------------------------------------------------------------------
async function addToDocuments(opportunityId, attachmentId, attachmentName) {
  try {
    if (!opportunityId) return;

    // El vinculo lead -> proyecto en esta instancia se hace via el campo
    // personalizado project.project.x_lead_id (crm.lead.project_ids, el
    // campo nativo, esta vacio en todos los leads reales probados).
    const projects = await odoo.searchRead(
      'project.project',
      [['x_lead_id', '=', opportunityId]],
      ['id', 'documents_folder_id'],
    );
    const projectWithFolder = projects.find(p => p.documents_folder_id);
    if (!projectWithFolder) return;
    const rootFolderId = projectWithFolder.documents_folder_id[0];

    const subfolders = await odoo.searchRead(
      'documents.document',
      [
        ['folder_id', '=', rootFolderId],
        ['is_folder', '=', true],
        ['name', 'ilike', '02_Ingenieria'],
      ],
      ['id', 'name'],
    );
    if (!subfolders.length) {
      console.warn('[generate-manual] WARNING: subcarpeta 02_Ingenieria no encontrada en proyecto, omitiendo Documents');
      return;
    }
    const ingenieriaFolderId = subfolders[0].id;

    // NOTA: no se pasa res_model/res_id aqui a proposito. Probado: si se
    // pasa res_model='sale.order' (sin res_id), Odoo sobreescribe el
    // res_id del ir.attachment original a 0, desvinculandolo del pedido.
    const docId = await odoo.create('documents.document', {
      name:          attachmentName,
      attachment_id: attachmentId,
      folder_id:     ingenieriaFolderId,
    });
    console.log(`[generate-manual] documents.document creado id=${docId} en carpeta 02_Ingenieria (folder_id=${ingenieriaFolderId})`);
  } catch (err) {
    console.warn(`[generate-manual] No se pudo crear documents.document: ${err.message}`);
  }
}
