/**
 * generate-ficha.js — Vercel serverless function
 * POST /api/generate-ficha
 *
 * Llamado por Odoo (base.automation) cuando se confirma una orden de venta.
 * Lee el pedido via XML-RPC, genera un PDF con portada Antrade + las paginas
 * reales del PDF adjunto de cada producto (sin pagina de especificaciones),
 * y lo sube como ir.attachment vinculado al sale.order.
 *
 * Variables de entorno requeridas (ademas de las de Odoo):
 *   FICHA_SECRET — token de autenticacion compartido con la server action de Odoo
 */

'use strict';

const path = require('path');
const fs = require('fs');
const { PDFDocument, rgb, StandardFonts } = require('pdf-lib');
const odoo = require('./_lib/odoo');

// ---------------------------------------------------------------------------
// Constantes de layout (A4 en puntos: 595 x 842)
// ---------------------------------------------------------------------------
const A4_W = 595;
const A4_H = 842;
const MARGIN = 50;
const COL_W = A4_W - MARGIN * 2;

const BLUE     = rgb(0,    0.231, 0.431);  // #003B6F — azul Antrade
const BLUE_LT  = rgb(0.88, 0.93,  0.97);  // fondo suave para encabezados de producto
const GRAY     = rgb(0.45, 0.45,  0.45);
const GRAY_LT  = rgb(0.85, 0.85,  0.85);
const BLACK    = rgb(0,    0,     0);
const WHITE    = rgb(1,    1,     1);

// Limite por adjunto para no exceder el timeout de Vercel (~10s hobby / 60s pro)
const MAX_ATT_BYTES = 500 * 1024; // 500 KB

// ---------------------------------------------------------------------------
// Labels bilingues (idioma segun partner.lang en Odoo)
// ---------------------------------------------------------------------------
const LABELS = {
  es: {
    title:     'FICHA TECNICA',
    client:    'Cliente',
    order:     'Pedido',
    date:      'Fecha/Hora',
    products:  'Productos incluidos',
    footer:    'Documento generado automaticamente por Antrade Servitech SL',
  },
  en: {
    title:     'TECHNICAL DATASHEET',
    client:    'Client',
    order:     'Order',
    date:      'Date/Time',
    products:  'Products included',
    footer:    'Document automatically generated by Antrade Servitech SL',
  },
};

// ---------------------------------------------------------------------------
// Handler principal
// ---------------------------------------------------------------------------
module.exports = async (req, res) => {
  if (req.method === 'OPTIONS') {
    return res.status(204).end();
  }
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // --- Autenticacion por secret ---
  // Acepta dos formatos:
  //   Llamada directa:   POST body { order_id, secret }
  //   Webhook de Odoo:   POST body { id, name, ... } + query ?secret=xxx
  const body = req.body || {};
  const order_id = body.order_id || body.id;
  const secret = body.secret || (req.query && req.query.secret);

  if (!process.env.FICHA_SECRET || secret !== process.env.FICHA_SECRET) {
    return res.status(401).json({ error: 'Unauthorized' });
  }
  if (!order_id) {
    return res.status(400).json({ error: 'order_id or id is required' });
  }

  try {
    const { pdfBytes, opportunityId } = await buildFicha(order_id);
    const attName = await uploadToOdoo(order_id, pdfBytes, opportunityId);
    return res.status(200).json({ success: true, attachment: attName });
  } catch (err) {
    console.error('[generate-ficha] ERROR:', err.message);
    return res.status(500).json({ error: err.message });
  }
};

// ---------------------------------------------------------------------------
// buildFicha — genera el PDF completo y devuelve bytes
// ---------------------------------------------------------------------------
async function buildFicha(orderId) {
  // 1. Leer order (primero: aporta partner_id y opportunity_id para los
  // siguientes pasos, no se puede paralelizar con nada)
  const orders = await odoo.searchRead(
    'sale.order',
    [['id', '=', orderId]],
    ['id', 'name', 'date_order', 'partner_id', 'opportunity_id'],
  );
  if (!orders.length) throw new Error(`sale.order id=${orderId} no encontrado`);
  const order = orders[0];
  // opportunity_id devuelto por Odoo como [id, 'name'] o false
  const opportunityId = Array.isArray(order.opportunity_id) ? order.opportunity_id[0] : null;

  // 2. Partner y lineas de pedido son independientes entre si -> en paralelo
  const [partners, lines] = await Promise.all([
    odoo.searchRead('res.partner', [['id', '=', order.partner_id[0]]], ['name', 'lang'], { limit: 1 }),
    odoo.searchRead(
      'sale.order.line',
      [['order_id', '=', orderId], ['product_id', '!=', false]],
      ['product_id', 'product_uom_qty'],
    ),
  ]);
  const lang = (partners[0] && partners[0].lang && partners[0].lang.startsWith('es')) ? 'es' : 'en';
  const L = LABELS[lang];

  const prodIds = [...new Set(lines.map(l => l.product_id[0]))];
  if (!prodIds.length) {
    throw new Error('La orden no tiene lineas de producto.');
  }

  // 3. product.product -> product_tmpl_id (necesario antes de poder leer
  // templates/adjuntos, no se puede paralelizar con el paso anterior)
  const prods = await odoo.searchRead(
    'product.product',
    [['id', 'in', prodIds]],
    ['id', 'product_tmpl_id', 'name', 'default_code'],
  );
  const tmplIds = [...new Set(prods.map(p => p.product_tmpl_id[0]))];

  // 4. product.template y metadata de adjuntos dependen solo de tmplIds,
  // son independientes entre si -> en paralelo
  const [tmpls, attMeta] = await Promise.all([
    odoo.searchRead('product.template', [['id', 'in', tmplIds]], ['id', 'name', 'default_code']),
    odoo.searchRead(
      'ir.attachment',
      [
        ['res_model', '=', 'product.template'],
        ['res_id', 'in', tmplIds],
        ['mimetype', '=', 'application/pdf'],
        ['name', 'not like', 'MANUAL_%'],
      ],
      ['id', 'name', 'res_id', 'file_size'],
    ),
  ]);
  const tmplById = Object.fromEntries(tmpls.map(t => [t.id, t]));

  // Un adjunto por producto (el mas pequeno dentro del limite)
  const bestAtt = {};
  for (const att of attMeta) {
    const tid = att.res_id;
    if (att.file_size > MAX_ATT_BYTES) continue;
    if (!bestAtt[tid] || att.file_size < bestAtt[tid].file_size) {
      bestAtt[tid] = att;
    }
  }

  // 5. Descargar datos binarios solo de los adjuntos seleccionados
  const selectedIds = Object.values(bestAtt).map(a => a.id);
  let attData = [];
  if (selectedIds.length) {
    attData = await odoo.searchRead(
      'ir.attachment',
      [['id', 'in', selectedIds]],
      ['id', 'res_id', 'name', 'raw'],
    );
  }
  const attByTmpl = {};
  for (const att of attData) {
    attByTmpl[att.res_id] = att;
  }

  // 6. Construir el PDF
  const pdfDoc = await PDFDocument.create();
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const regFont  = await pdfDoc.embedFont(StandardFonts.Helvetica);

  // Logo Antrade
  let logoImage = null;
  try {
    const logoPath = path.join(__dirname, '../public/logo-antrade.png');
    const logoBytes = fs.readFileSync(logoPath);
    logoImage = await pdfDoc.embedPng(logoBytes);
  } catch (_) { /* sin logo, continuar */ }

  // Fecha y hora de generacion del documento (timestamp, no la fecha del pedido)
  const generatedAtStr = new Date().toLocaleString(lang === 'es' ? 'es-ES' : 'en-GB', {
    dateStyle: 'short',
    timeStyle: 'short',
  });

  // --- Pagina de portada ---
  addCoverPage(pdfDoc, boldFont, regFont, logoImage, order, partners[0], tmplIds, tmplById, generatedAtStr, L);

  // --- Paginas por producto: solo las paginas reales del PDF adjunto,
  // sin pagina de especificaciones. Si no tiene adjunto, se omite. ---
  for (const tmplId of tmplIds) {
    const tmpl = tmplById[tmplId];
    if (!tmpl) continue;

    const att = attByTmpl[tmplId];
    if (!att || !att.raw) continue;
    try {
      const attPdfBytes = Buffer.from(att.raw, 'base64');
      const src = await PDFDocument.load(attPdfBytes, { ignoreEncryption: true });
      const pages = await pdfDoc.copyPages(src, src.getPageIndices());
      for (const p of pages) pdfDoc.addPage(p);
    } catch (e) {
      console.warn(`[generate-ficha] No se pudo incrustar adjunto ${att.name}: ${e.message}`);
    }
  }

  return { pdfBytes: await pdfDoc.save(), opportunityId };
}

// ---------------------------------------------------------------------------
// addCoverPage
// ---------------------------------------------------------------------------
function addCoverPage(doc, bold, reg, logo, order, partner, tmplIds, tmplById, dateStr, L) {
  const page = doc.addPage([A4_W, A4_H]);

  // Barra azul superior
  page.drawRectangle({ x: 0, y: A4_H - 90, width: A4_W, height: 90, color: BLUE });

  // Logo
  if (logo) {
    const dims = logo.scaleToFit(160, 50);
    page.drawImage(logo, {
      x: MARGIN,
      y: A4_H - 90 + (90 - dims.height) / 2,
      width: dims.width,
      height: dims.height,
    });
  }

  // Antrade Servitech SL (derecha del header)
  page.drawText('Antrade Servitech SL', {
    x: A4_W - MARGIN - 160,
    y: A4_H - 55,
    size: 11,
    font: bold,
    color: WHITE,
  });

  // Titulo
  page.drawText(L.title, {
    x: MARGIN,
    y: A4_H - 130,
    size: 22,
    font: bold,
    color: BLUE,
  });

  // Linea divisoria
  page.drawLine({
    start: { x: MARGIN, y: A4_H - 140 },
    end:   { x: A4_W - MARGIN, y: A4_H - 140 },
    thickness: 1,
    color: BLUE_LT,
  });

  // Datos del pedido
  const infoY = A4_H - 170;
  const rows = [
    [L.client, partner ? partner.name : (order.partner_id[1] || '')],
    [L.order,  order.name],
    [L.date,   dateStr],
  ];
  rows.forEach(([label, value], i) => {
    const y = infoY - i * 22;
    page.drawText(label + ':', { x: MARGIN, y, size: 11, font: bold, color: GRAY });
    page.drawText(String(value), { x: MARGIN + 110, y, size: 11, font: reg, color: BLACK });
  });

  // Lista de productos
  const listTitle = L.products;
  const listY = infoY - rows.length * 22 - 30;
  page.drawText(listTitle, { x: MARGIN, y: listY, size: 11, font: bold, color: GRAY });

  let itemY = listY - 22;
  tmplIds.forEach((tid, idx) => {
    const t = tmplById[tid];
    if (!t) return;
    const code = t.default_code ? ` (${t.default_code})` : '';
    const label = safeText(`${idx + 1}. ${t.name}${code}`);
    page.drawText(label, { x: MARGIN + 10, y: itemY, size: 10, font: reg, color: BLACK });
    itemY -= 18;
  });

  // Footer
  drawFooter(page, reg, L.footer, 1);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function drawFooter(page, font, text, pageNum) {
  page.drawLine({
    start: { x: MARGIN, y: 40 },
    end:   { x: A4_W - MARGIN, y: 40 },
    thickness: 0.5,
    color: GRAY_LT,
  });
  page.drawText(safeText(text), {
    x: MARGIN,
    y: 26,
    size: 8,
    font,
    color: GRAY,
  });
  if (pageNum !== null) {
    page.drawText(String(pageNum), {
      x: A4_W - MARGIN - 10,
      y: 26,
      size: 8,
      font,
      color: GRAY,
    });
  }
}

/** Elimina caracteres fuera del rango Latin-1 que pdf-lib no maneja con StandardFonts */
function safeText(str) {
  return (str || '').replace(/[^\x00-\xFF]/g, '?');
}

// ---------------------------------------------------------------------------
// uploadToOdoo — sube el PDF como ir.attachment en el sale.order y,
// si existe, tambien en el crm.lead vinculado (opportunity_id).
// ---------------------------------------------------------------------------
async function uploadToOdoo(orderId, pdfBytes, opportunityId) {
  // Leer nombre del pedido para el nombre del adjunto
  const orders = await odoo.searchRead(
    'sale.order',
    [['id', '=', orderId]],
    ['name'],
    { limit: 1 },
  );
  const orderName = orders.length ? orders[0].name : `order-${orderId}`;
  const attName   = `Ficha_Tecnica_${orderName}.pdf`;
  const b64 = Buffer.from(pdfBytes).toString('base64');

  // --- Adjunto en sale.order ---
  // Borrar adjunto previo del mismo nombre si existe (idempotente)
  const existingSO = await odoo.searchRead(
    'ir.attachment',
    [
      ['res_model', '=', 'sale.order'],
      ['res_id', '=', orderId],
      ['name', '=', attName],
    ],
    ['id'],
  );
  if (existingSO.length) {
    await odoo.execute('ir.attachment', 'unlink', [existingSO.map(a => a.id)]);
  }
  const soAttId = await odoo.create('ir.attachment', {
    name:      attName,
    type:      'binary',
    raw:       b64,
    res_model: 'sale.order',
    res_id:    orderId,
    mimetype:  'application/pdf',
  });

  // --- Adjunto en crm.lead (si existe opportunity_id) ---
  if (opportunityId && opportunityId > 0) {
    try {
      const existingCRM = await odoo.searchRead(
        'ir.attachment',
        [
          ['res_model', '=', 'crm.lead'],
          ['res_id', '=', opportunityId],
          ['name', '=', attName],
        ],
        ['id'],
      );
      if (existingCRM.length) {
        await odoo.execute('ir.attachment', 'unlink', [existingCRM.map(a => a.id)]);
      }
      await odoo.create('ir.attachment', {
        name:      attName,
        type:      'binary',
        raw:       b64,
        res_model: 'crm.lead',
        res_id:    opportunityId,
        mimetype:  'application/pdf',
      });
      console.log(`[generate-ficha] Adjunto subido tambien a crm.lead id=${opportunityId}`);
    } catch (crmErr) {
      // Fallo no fatal: el adjunto en sale.order ya existe
      console.warn(`[generate-ficha] No se pudo subir adjunto a crm.lead id=${opportunityId}: ${crmErr.message}`);
    }
  }

  await addToDocuments(opportunityId, soAttId, attName);

  return attName;
}

// ---------------------------------------------------------------------------
// addToDocuments — copia (envuelve) el adjunto del sale.order como
// documents.document dentro de la subcarpeta 02_Ingenieria del proyecto
// vinculado al lead. Bonus: cualquier fallo se loggea y se ignora, nunca
// debe bloquear la generacion/subida del PDF.
// ---------------------------------------------------------------------------
async function addToDocuments(opportunityId, attachmentId, attachmentName) {
  try {
    if (!opportunityId) return;

    // El vinculo lead -> proyecto en esta instancia se hace via el campo
    // personalizado project.project.x_lead_id (crm.lead.project_ids, el
    // campo nativo, esta vacio en todos los leads reales probados).
    const projects = await odoo.searchRead(
      'project.project',
      [['x_lead_id', '=', opportunityId]],
      ['id', 'documents_folder_id'],
    );
    const projectWithFolder = projects.find(p => p.documents_folder_id);
    if (!projectWithFolder) return;
    const rootFolderId = projectWithFolder.documents_folder_id[0];

    const subfolders = await odoo.searchRead(
      'documents.document',
      [
        ['folder_id', '=', rootFolderId],
        ['is_folder', '=', true],
        ['name', 'ilike', '02_Ingenieria'],
      ],
      ['id', 'name'],
    );
    if (!subfolders.length) {
      console.warn('[generate-ficha] WARNING: subcarpeta 02_Ingenieria no encontrada en proyecto, omitiendo Documents');
      return;
    }
    const ingenieriaFolderId = subfolders[0].id;

    // NOTA: no se pasa res_model/res_id aqui a proposito. Probado: si se
    // pasa res_model='sale.order' (sin res_id), Odoo sobreescribe el
    // res_id del ir.attachment original a 0, desvinculandolo del pedido.
    const docId = await odoo.create('documents.document', {
      name:          attachmentName,
      attachment_id: attachmentId,
      folder_id:     ingenieriaFolderId,
    });
    console.log(`[generate-ficha] documents.document creado id=${docId} en carpeta 02_Ingenieria (folder_id=${ingenieriaFolderId})`);
  } catch (err) {
    console.warn(`[generate-ficha] No se pudo crear documents.document: ${err.message}`);
  }
}
