/**
 * generate-manual.js — Vercel serverless function
 * POST /api/generate-manual
 *
 * Genera el manual de montaje de un pedido. Dos caminos segun el pedido:
 *
 *   FAST PATH (pedido de una sola familia): el PDF fusionado de esa familia
 *   ya existe en Odoo como ir.attachment (ver 12_merge_family_manuals.py).
 *   En vez de descargar + reconstruir + resubir, se copia server-side con
 *   ir.attachment.copy() (sin transferir datos, <5s).
 *
 *   SLOW PATH (pedido con mas de una familia): descarga los PDFs fusionados
 *   de cada familia involucrada, los combina en un solo PDF con portada
 *   Antrade, y lo sube (con fallback de particion en 2 mitades si supera el
 *   limite de subida del servidor).
 *
 * En ambos casos se sube como ir.attachment al sale.order y, si existe,
 * tambien al crm.lead vinculado.
 *
 * Misma autenticacion que generate-ficha.js (FICHA_SECRET).
 */

'use strict';

const path = require('path');
const fs = require('fs');
const { PDFDocument, rgb, StandardFonts } = require('pdf-lib');
const odoo = require('./_lib/odoo');

const A4_W = 595;
const A4_H = 842;
const MARGIN = 50;

const BLUE    = rgb(0,    0.231, 0.431);
const BLUE_LT = rgb(0.88, 0.93,  0.97);
const GRAY    = rgb(0.45, 0.45,  0.45);
const GRAY_LT = rgb(0.85, 0.85,  0.85);
const BLACK   = rgb(0,    0,     0);
const WHITE   = rgb(1,    1,     1);

const LABELS = {
  es: {
    title:    'MANUAL DE MONTAJE',
    client:   'Cliente',
    order:    'Pedido',
    date:     'Fecha',
    products: 'Productos incluidos',
    footer:   'Documento generado automaticamente por Antrade Servitech SL',
  },
  en: {
    title:    'ASSEMBLY MANUAL',
    client:   'Client',
    order:    'Order',
    date:     'Date',
    products: 'Products included',
    footer:   'Document automatically generated by Antrade Servitech SL',
  },
};

// ---------------------------------------------------------------------------
// Handler principal
// ---------------------------------------------------------------------------
module.exports = async (req, res) => {
  if (req.method === 'OPTIONS') {
    return res.status(204).end();
  }
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const body = req.body || {};
  const order_id = body.order_id || body.id;
  const secret = body.secret || (req.query && req.query.secret);

  if (!process.env.FICHA_SECRET || secret !== process.env.FICHA_SECRET) {
    return res.status(401).json({ error: 'Unauthorized' });
  }
  if (!order_id) {
    return res.status(400).json({ error: 'order_id or id is required' });
  }

  try {
    const situation = await locateManuals(order_id);

    if (!situation.tmplIdsWithManual.length) {
      return res.status(200).json({
        success: false,
        sin_manual: situation.sinManual,
        message: 'No hay manuales disponibles',
      });
    }

    // FAST PATH: todos los adjuntos a usar pertenecen a la misma familia
    // (mismo res_id de origen) -> copy() server-side, sin descargar nada.
    const fastPath = situation.familyResIds.size === 1;

    let attName;
    if (fastPath) {
      attName = await fastPathCopy(order_id, situation);
    } else {
      const pdfBytes = await buildManualPdf(situation);
      attName = await uploadToOdoo(order_id, pdfBytes, situation.opportunityId);
    }

    return res.status(200).json({
      success: true,
      attachment: attName,
      sin_manual: situation.sinManual,
      fast_path: fastPath,
    });
  } catch (err) {
    console.error('[generate-manual] ERROR:', err.message);
    return res.status(500).json({ error: err.message });
  }
};

// ---------------------------------------------------------------------------
// locateManuals — lee el pedido y localiza los manuales aplicables (PASO A +
// PASO B), sin descargar binarios. Devuelve todo lo necesario para decidir
// fast path vs slow path y para ejecutar cualquiera de los dos.
// ---------------------------------------------------------------------------
async function locateManuals(orderId) {
  // 1. Leer order
  const orders = await odoo.searchRead(
    'sale.order',
    [['id', '=', orderId]],
    ['id', 'name', 'date_order', 'partner_id', 'opportunity_id'],
  );
  if (!orders.length) throw new Error(`sale.order id=${orderId} no encontrado`);
  const order = orders[0];
  const opportunityId = Array.isArray(order.opportunity_id) ? order.opportunity_id[0] : null;
  const orderName = order.name;

  // 2. Idioma del cliente
  const partners = await odoo.searchRead(
    'res.partner',
    [['id', '=', order.partner_id[0]]],
    ['name', 'lang'],
    { limit: 1 },
  );
  const lang = (partners[0] && partners[0].lang && partners[0].lang.startsWith('es')) ? 'es' : 'en';
  const L = LABELS[lang];

  // 3. Lineas de pedido -> product_ids unicos
  const lines = await odoo.searchRead(
    'sale.order.line',
    [['order_id', '=', orderId], ['product_id', '!=', false]],
    ['product_id', 'product_uom_qty'],
  );
  const prodIds = [...new Set(lines.map(l => l.product_id[0]))];
  if (!prodIds.length) throw new Error('La orden no tiene lineas de producto.');

  // 4. product.product -> product_tmpl_id
  const prods = await odoo.searchRead(
    'product.product',
    [['id', 'in', prodIds]],
    ['id', 'product_tmpl_id'],
  );
  const tmplIds = [...new Set(prods.map(p => p.product_tmpl_id[0]))];

  // 5. product.template -> name, default_code, categ_id
  const tmpls = await odoo.searchRead(
    'product.template',
    [['id', 'in', tmplIds]],
    ['id', 'name', 'default_code', 'categ_id'],
  );
  const tmplById = Object.fromEntries(tmpls.map(t => [t.id, t]));

  // --- PASO A: manual fusionado propio de cada producto ---
  const manualsByTmpl = {};
  const ownManuals = await odoo.searchRead(
    'ir.attachment',
    [
      ['res_model', '=', 'product.template'],
      ['res_id', 'in', tmplIds],
      ['name', 'like', 'MANUAL_FAMILIA_%'],
      ['mimetype', '=', 'application/pdf'],
    ],
    ['id', 'name', 'res_id'],
  );
  for (const att of ownManuals) {
    if (!manualsByTmpl[att.res_id]) manualsByTmpl[att.res_id] = [];
    manualsByTmpl[att.res_id].push(att);
  }

  // --- PASO B: para los productos sin manual propio, buscar en hermanos
  // de la misma categoria (cubre al producto representativo de la familia) ---
  const missingTmplIds = tmplIds.filter(tid => !manualsByTmpl[tid] || !manualsByTmpl[tid].length);
  if (missingTmplIds.length) {
    const categIds = [...new Set(
      missingTmplIds
        .map(tid => tmplById[tid] && tmplById[tid].categ_id)
        .filter(Boolean)
        .map(c => (Array.isArray(c) ? c[0] : c)),
    )];

    if (categIds.length) {
      const siblings = await odoo.searchRead(
        'product.template',
        [['categ_id', 'in', categIds]],
        ['id', 'categ_id'],
      );
      const siblingIdsByCateg = {};
      for (const s of siblings) {
        const cid = Array.isArray(s.categ_id) ? s.categ_id[0] : s.categ_id;
        if (!siblingIdsByCateg[cid]) siblingIdsByCateg[cid] = [];
        siblingIdsByCateg[cid].push(s.id);
      }

      const allSiblingIds = [...new Set(siblings.map(s => s.id))];
      const siblingManuals = allSiblingIds.length
        ? await odoo.searchRead(
            'ir.attachment',
            [
              ['res_model', '=', 'product.template'],
              ['res_id', 'in', allSiblingIds],
              ['name', 'like', 'MANUAL_FAMILIA_%'],
              ['mimetype', '=', 'application/pdf'],
            ],
            ['id', 'name', 'res_id'],
          )
        : [];
      const manualsBySiblingId = {};
      for (const att of siblingManuals) {
        if (!manualsBySiblingId[att.res_id]) manualsBySiblingId[att.res_id] = [];
        manualsBySiblingId[att.res_id].push(att);
      }

      for (const tid of missingTmplIds) {
        const tmpl = tmplById[tid];
        if (!tmpl || !tmpl.categ_id) continue;
        const cid = Array.isArray(tmpl.categ_id) ? tmpl.categ_id[0] : tmpl.categ_id;
        const candidateIds = (siblingIdsByCateg[cid] || []).filter(sid => sid !== tid);
        for (const sid of candidateIds) {
          if (manualsBySiblingId[sid] && manualsBySiblingId[sid].length) {
            manualsByTmpl[tid] = manualsBySiblingId[sid];
            break;
          }
        }
      }
    }
  }

  // --- Productos sin manual tras los dos pasos ---
  const sinManual = [];
  for (const tid of tmplIds) {
    if (!manualsByTmpl[tid] || !manualsByTmpl[tid].length) {
      const tmpl = tmplById[tid];
      sinManual.push(tmpl ? (tmpl.default_code || tmpl.name) : `id_${tid}`);
    }
  }

  const tmplIdsWithManual = tmplIds.filter(tid => manualsByTmpl[tid] && manualsByTmpl[tid].length);

  // Adjuntos unicos que se van a usar (deduplicados por id) y de cuantas
  // familias distintas provienen (por res_id del product.template origen).
  // Si todos vienen del mismo res_id -> 1 sola familia -> fast path.
  const usedAttsById = {};
  for (const tid of tmplIdsWithManual) {
    for (const att of manualsByTmpl[tid]) {
      usedAttsById[att.id] = att;
    }
  }
  const usedAtts = Object.values(usedAttsById);
  const familyResIds = new Set(usedAtts.map(a => a.res_id));

  return {
    order, orderName, opportunityId, lang, L, partner: partners[0],
    tmplIds, tmplById, manualsByTmpl, tmplIdsWithManual, sinManual,
    usedAtts, familyResIds,
  };
}

// ---------------------------------------------------------------------------
// fastPathCopy — pedido de una sola familia: copia server-side el/los PDF(s)
// fusionados de esa familia con ir.attachment.copy(), sin descargar ni
// reconstruir nada. NOTA: el resultado es el PDF de manuales tal cual existe
// en Odoo, sin portada Antrade (a diferencia del slow path).
// ---------------------------------------------------------------------------
async function fastPathCopy(orderId, situation) {
  const { opportunityId, orderName, usedAtts } = situation;
  const sorted = [...usedAtts].sort((a, b) => a.name.localeCompare(b.name));
  const baseNames = sorted.length === 1
    ? [`Manual_Montaje_${orderName}.pdf`]
    : sorted.map((_, i) => `Manual_Montaje_${orderName}_part${i + 1}of${sorted.length}.pdf`);

  // Idempotente: borrar copias previas con el mismo patron de nombre
  const existingSO = await odoo.searchRead(
    'ir.attachment',
    [
      ['res_model', '=', 'sale.order'],
      ['res_id', '=', orderId],
      ['name', 'like', `Manual_Montaje_${orderName}%`],
    ],
    ['id'],
  );
  if (existingSO.length) {
    await odoo.execute('ir.attachment', 'unlink', [existingSO.map(a => a.id)]);
  }

  const newAtts = [];
  for (let i = 0; i < sorted.length; i++) {
    const result = await odoo.execute('ir.attachment', 'copy', [[sorted[i].id], {
      name:      baseNames[i],
      res_model: 'sale.order',
      res_id:    orderId,
      res_name:  orderName,
    }]);
    const newId = Array.isArray(result) ? result[0] : result;
    newAtts.push({ id: newId, name: baseNames[i] });
  }
  console.log(`[generate-manual] (fast path) ${newAtts.length} adjunto(s) copiado(s) server-side al sale.order id=${orderId}`);

  if (opportunityId && opportunityId > 0) {
    try {
      const existingCRM = await odoo.searchRead(
        'ir.attachment',
        [
          ['res_model', '=', 'crm.lead'],
          ['res_id', '=', opportunityId],
          ['name', 'like', `Manual_Montaje_${orderName}%`],
        ],
        ['id'],
      );
      if (existingCRM.length) {
        await odoo.execute('ir.attachment', 'unlink', [existingCRM.map(a => a.id)]);
      }
      for (let i = 0; i < sorted.length; i++) {
        await odoo.execute('ir.attachment', 'copy', [[sorted[i].id], {
          name:      baseNames[i],
          res_model: 'crm.lead',
          res_id:    opportunityId,
          res_name:  orderName,
        }]);
      }
      console.log(`[generate-manual] (fast path) Adjunto(s) copiado(s) tambien a crm.lead id=${opportunityId}`);
    } catch (crmErr) {
      console.warn(`[generate-manual] (fast path) No se pudo copiar adjunto a crm.lead id=${opportunityId}: ${crmErr.message}`);
    }
  }

  for (const att of newAtts) {
    await addToDocuments(opportunityId, att.id, att.name);
  }

  return newAtts.length === 1 ? newAtts[0].name : newAtts.map(a => a.name).join(', ');
}

// ---------------------------------------------------------------------------
// buildManualPdf — slow path: descarga los manuales de mas de una familia y
// los combina en un solo PDF con portada Antrade.
// ---------------------------------------------------------------------------
async function buildManualPdf(situation) {
  const { order, partner, lang, L, tmplIds, tmplById, manualsByTmpl, tmplIdsWithManual, usedAtts } = situation;

  // --- Descargar binarios de los manuales seleccionados (sin duplicar ids) ---
  // Se ha comprobado que dos descargas grandes (>=20MB) seguidas en la misma
  // invocacion, sin pausa entre ellas, hacen que el servidor Odoo SaaS trial
  // corte la conexion ("Unknown XML-RPC tag 'TITLE'"). Cada descarga
  // individual reintenta hasta 3 veces, con una pequena pausa entre
  // adjuntos distintos para no encadenar dos descargas pesadas.
  const allAttIds = [...new Set(usedAtts.map(a => a.id))];
  const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
  const attDataById = {};
  for (let i = 0; i < allAttIds.length; i++) {
    const id = allAttIds[i];
    if (i > 0) await sleep(1500);
    let lastErr = null;
    for (let attempt = 1; attempt <= 3; attempt++) {
      try {
        const single = await odoo.searchRead(
          'ir.attachment',
          [['id', '=', id]],
          ['id', 'name', 'raw'],
        );
        if (single.length) attDataById[single[0].id] = single[0];
        lastErr = null;
        break;
      } catch (e) {
        lastErr = e;
        console.warn(`[generate-manual] Intento ${attempt}/3 de descarga del adjunto id=${id} fallido: ${e.message}`);
        if (attempt < 3) await sleep(2000);
      }
    }
    if (lastErr) {
      console.warn(`[generate-manual] No se pudo descargar adjunto id=${id} tras 3 intentos: ${lastErr.message}`);
    }
  }

  // --- Construir el PDF ---
  const pdfDoc = await PDFDocument.create();
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const regFont  = await pdfDoc.embedFont(StandardFonts.Helvetica);

  let logoImage = null;
  try {
    const logoPath = path.join(__dirname, '../public/logo-antrade.png');
    const logoBytes = fs.readFileSync(logoPath);
    logoImage = await pdfDoc.embedPng(logoBytes);
  } catch (_) { /* sin logo, continuar */ }

  const dateStr = order.date_order
    ? new Date(order.date_order).toLocaleDateString(lang === 'es' ? 'es-ES' : 'en-GB')
    : '';

  addCoverPage(pdfDoc, boldFont, regFont, logoImage, order, partner, tmplIds, tmplById, dateStr, L);

  // Embebe cada adjunto una sola vez aunque varios productos compartan
  // el mismo manual heredado (PASO B). Orden alfabetico por nombre para
  // que, si el merged esta partido en 2, part1of2 se incruste antes que
  // part2of2.
  const embeddedIds = new Set();
  for (const tid of tmplIdsWithManual) {
    const attsForTid = [...manualsByTmpl[tid]].sort((a, b) => a.name.localeCompare(b.name));
    for (const att of attsForTid) {
      if (embeddedIds.has(att.id)) continue;
      embeddedIds.add(att.id);

      const full = attDataById[att.id];
      if (!full || !full.raw) continue;
      try {
        const pdfBytes = Buffer.from(full.raw, 'base64');
        const src = await PDFDocument.load(pdfBytes, { ignoreEncryption: true });
        const pages = await pdfDoc.copyPages(src, src.getPageIndices());
        for (const p of pages) pdfDoc.addPage(p);
      } catch (e) {
        console.warn(`[generate-manual] No se pudo incrustar ${att.name}: ${e.message}`);
      }
    }
  }

  return pdfDoc.save();
}

// ---------------------------------------------------------------------------
// addCoverPage
// ---------------------------------------------------------------------------
function addCoverPage(doc, bold, reg, logo, order, partner, tmplIds, tmplById, dateStr, L) {
  const page = doc.addPage([A4_W, A4_H]);

  page.drawRectangle({ x: 0, y: A4_H - 90, width: A4_W, height: 90, color: BLUE });

  if (logo) {
    const dims = logo.scaleToFit(160, 50);
    page.drawImage(logo, {
      x: MARGIN,
      y: A4_H - 90 + (90 - dims.height) / 2,
      width: dims.width,
      height: dims.height,
    });
  }

  page.drawText('Antrade Servitech SL', {
    x: A4_W - MARGIN - 160,
    y: A4_H - 55,
    size: 11,
    font: bold,
    color: WHITE,
  });

  page.drawText(L.title, {
    x: MARGIN,
    y: A4_H - 130,
    size: 22,
    font: bold,
    color: BLUE,
  });

  page.drawLine({
    start: { x: MARGIN, y: A4_H - 140 },
    end:   { x: A4_W - MARGIN, y: A4_H - 140 },
    thickness: 1,
    color: BLUE_LT,
  });

  const infoY = A4_H - 170;
  const rows = [
    [L.client, partner ? partner.name : (order.partner_id[1] || '')],
    [L.order,  order.name],
    [L.date,   dateStr],
  ];
  rows.forEach(([label, value], i) => {
    const y = infoY - i * 22;
    page.drawText(label + ':', { x: MARGIN, y, size: 11, font: bold, color: GRAY });
    page.drawText(String(value), { x: MARGIN + 110, y, size: 11, font: reg, color: BLACK });
  });

  const listY = infoY - rows.length * 22 - 30;
  page.drawText(L.products, { x: MARGIN, y: listY, size: 11, font: bold, color: GRAY });

  let itemY = listY - 22;
  tmplIds.forEach((tid, idx) => {
    const t = tmplById[tid];
    if (!t) return;
    const code = t.default_code ? ` (${t.default_code})` : '';
    const label = safeText(`${idx + 1}. ${t.name}${code}`);
    page.drawText(label, { x: MARGIN + 10, y: itemY, size: 10, font: reg, color: BLACK });
    itemY -= 18;
  });

  drawFooter(page, reg, L.footer, 1);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function drawFooter(page, font, text, pageNum) {
  page.drawLine({
    start: { x: MARGIN, y: 40 },
    end:   { x: A4_W - MARGIN, y: 40 },
    thickness: 0.5,
    color: GRAY_LT,
  });
  page.drawText(safeText(text), { x: MARGIN, y: 26, size: 8, font, color: GRAY });
  if (pageNum !== null) {
    page.drawText(String(pageNum), { x: A4_W - MARGIN - 10, y: 26, size: 8, font, color: GRAY });
  }
}

function safeText(str) {
  return (str || '').replace(/[^\x00-\xFF]/g, '?');
}

// ---------------------------------------------------------------------------
// uploadOneAttachment — sube pdfBytes como ir.attachment, con reintentos.
// Devuelve el id creado o null si fallan todos los intentos.
// ---------------------------------------------------------------------------
async function uploadOneAttachment(name, pdfBytes, resModel, resId, maxAttempts) {
  const b64 = Buffer.from(pdfBytes).toString('base64');
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      const attId = await odoo.create('ir.attachment', {
        name, type: 'binary', raw: b64,
        res_model: resModel, res_id: resId, mimetype: 'application/pdf',
      });
      return attId;
    } catch (e) {
      console.warn(`[generate-manual] Intento ${attempt}/${maxAttempts} de subida de "${name}" fallido: ${e.message}`);
      if (attempt < maxAttempts) await new Promise((r) => setTimeout(r, 2000));
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// uploadPdfWithSplitFallback — sube pdfBytes con el nombre base dado.
// Si la subida falla repetidamente (sospecha de limite de tamano de
// payload en el servidor Odoo SaaS trial -- comprobado: pedidos que
// combinan 2 familias completas pueden superar ~64MB), parte el PDF por la
// mitad de sus paginas y reintenta cada mitad por separado (recursivo).
// Devuelve una lista de { name, attId }.
// ---------------------------------------------------------------------------
async function uploadPdfWithSplitFallback(baseName, pdfBytes, resModel, resId) {
  const attId = await uploadOneAttachment(baseName, pdfBytes, resModel, resId, 3);
  if (attId !== null) return [{ name: baseName, attId }];

  const src = await PDFDocument.load(pdfBytes, { ignoreEncryption: true });
  const pageCount = src.getPageCount();
  if (pageCount <= 1) {
    console.warn(`[generate-manual] No se pudo subir "${baseName}" (1 sola pagina, no se puede partir mas).`);
    return [];
  }

  console.warn(`[generate-manual] Subida de "${baseName}" fallo repetidamente (posible limite de tamano del servidor). Partiendo PDF en 2 mitades de paginas...`);
  const mid = Math.ceil(pageCount / 2);
  const ranges = [[0, mid], [mid, pageCount]];
  const nameRoot = baseName.endsWith('.pdf') ? baseName.slice(0, -4) : baseName;

  const results = [];
  for (let i = 0; i < ranges.length; i++) {
    const [start, end] = ranges[i];
    const half = await PDFDocument.create();
    const indices = [];
    for (let p = start; p < end; p++) indices.push(p);
    const pages = await half.copyPages(src, indices);
    for (const p of pages) half.addPage(p);
    const halfBytes = await half.save();
    const halfName = `${nameRoot}_part${i + 1}of2.pdf`;
    const subResults = await uploadPdfWithSplitFallback(halfName, halfBytes, resModel, resId);
    results.push(...subResults);
  }
  return results;
}

// ---------------------------------------------------------------------------
// uploadToOdoo — sube el PDF como ir.attachment al sale.order y, si existe,
// tambien al crm.lead vinculado (opportunity_id). Solo se usa en el slow path.
// ---------------------------------------------------------------------------
async function uploadToOdoo(orderId, pdfBytes, opportunityId) {
  const orders = await odoo.searchRead(
    'sale.order',
    [['id', '=', orderId]],
    ['name'],
    { limit: 1 },
  );
  const orderName = orders.length ? orders[0].name : `order-${orderId}`;
  const attName   = `Manual_Montaje_${orderName}.pdf`;

  const existingSO = await odoo.searchRead(
    'ir.attachment',
    [
      ['res_model', '=', 'sale.order'],
      ['res_id', '=', orderId],
      ['name', 'like', `Manual_Montaje_${orderName}%`],
    ],
    ['id'],
  );
  if (existingSO.length) {
    await odoo.execute('ir.attachment', 'unlink', [existingSO.map(a => a.id)]);
  }
  const soParts = await uploadPdfWithSplitFallback(attName, pdfBytes, 'sale.order', orderId);
  if (!soParts.length) {
    throw new Error(`No se pudo subir "${attName}" al sale.order (ni partido en mitades).`);
  }

  if (opportunityId && opportunityId > 0) {
    try {
      const existingCRM = await odoo.searchRead(
        'ir.attachment',
        [
          ['res_model', '=', 'crm.lead'],
          ['res_id', '=', opportunityId],
          ['name', 'like', `Manual_Montaje_${orderName}%`],
        ],
        ['id'],
      );
      if (existingCRM.length) {
        await odoo.execute('ir.attachment', 'unlink', [existingCRM.map(a => a.id)]);
      }
      const crmParts = await uploadPdfWithSplitFallback(attName, pdfBytes, 'crm.lead', opportunityId);
      if (crmParts.length) {
        console.log(`[generate-manual] Adjunto subido tambien a crm.lead id=${opportunityId} (${crmParts.length} parte(s))`);
      } else {
        console.warn(`[generate-manual] No se pudo subir adjunto a crm.lead id=${opportunityId} (ni partido)`);
      }
    } catch (crmErr) {
      console.warn(`[generate-manual] No se pudo subir adjunto a crm.lead id=${opportunityId}: ${crmErr.message}`);
    }
  }

  for (const part of soParts) {
    await addToDocuments(opportunityId, part.attId, part.name);
  }

  return soParts.length === 1 ? soParts[0].name : soParts.map(p => p.name).join(', ');
}

// ---------------------------------------------------------------------------
// addToDocuments — copia (envuelve) el adjunto del sale.order como
// documents.document dentro de la subcarpeta 02_Ingenieria del proyecto
// vinculado al lead. Bonus: cualquier fallo se loggea y se ignora, nunca
// debe bloquear la generacion/subida del PDF.
// ---------------------------------------------------------------------------
async function addToDocuments(opportunityId, attachmentId, attachmentName) {
  try {
    if (!opportunityId) return;

    // El vinculo lead -> proyecto en esta instancia se hace via el campo
    // personalizado project.project.x_lead_id (crm.lead.project_ids, el
    // campo nativo, esta vacio en todos los leads reales probados).
    const projects = await odoo.searchRead(
      'project.project',
      [['x_lead_id', '=', opportunityId]],
      ['id', 'documents_folder_id'],
    );
    const projectWithFolder = projects.find(p => p.documents_folder_id);
    if (!projectWithFolder) return;
    const rootFolderId = projectWithFolder.documents_folder_id[0];

    const subfolders = await odoo.searchRead(
      'documents.document',
      [
        ['folder_id', '=', rootFolderId],
        ['is_folder', '=', true],
        ['name', 'ilike', '02_Ingenieria'],
      ],
      ['id', 'name'],
    );
    if (!subfolders.length) {
      console.warn('[generate-manual] WARNING: subcarpeta 02_Ingenieria no encontrada en proyecto, omitiendo Documents');
      return;
    }
    const ingenieriaFolderId = subfolders[0].id;

    // NOTA: no se pasa res_model/res_id aqui a proposito. Probado: si se
    // pasa res_model='sale.order' (sin res_id), Odoo sobreescribe el
    // res_id del ir.attachment original a 0, desvinculandolo del pedido.
    const docId = await odoo.create('documents.document', {
      name:          attachmentName,
      attachment_id: attachmentId,
      folder_id:     ingenieriaFolderId,
    });
    console.log(`[generate-manual] documents.document creado id=${docId} en carpeta 02_Ingenieria (folder_id=${ingenieriaFolderId})`);
  } catch (err) {
    console.warn(`[generate-manual] No se pudo crear documents.document: ${err.message}`);
  }
}
